// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAOazpaf_nS0yqYVUkenpRzvKwn4mUF2k',
    appId: '1:410377860705:android:a4ba9050f0f7afcb7d5c20',
    messagingSenderId: '410377860705',
    projectId: 'fb-auth-bloc-202304030046',
    storageBucket: 'fb-auth-bloc-202304030046.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF3MVz2XhHPOAZV6Yr936L7A2uNYLwwuE',
    appId: '1:410377860705:ios:349b1b66b934c8c47d5c20',
    messagingSenderId: '410377860705',
    projectId: 'fb-auth-bloc-202304030046',
    storageBucket: 'fb-auth-bloc-202304030046.appspot.com',
    iosClientId: '410377860705-8ohuaqs07hp3fepd2hnkgtrakum9ekdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbAuthBloc',
  );
}
